name: CI
on: [push,pull_request]

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'
      - uses: golangci/golangci-lint-action@v2
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: make test